parameters:
#    mainproject.example.class: main\projectBundle\Example

services:
#    mainproject.example:
#        class: %mainproject.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
