<?php

namespace main\projectBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CatalogueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogueRepository extends EntityRepository
{
}
